# Generated by Django 4.1 on 2022-08-25 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_category_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='descriptions',
            new_name='discriptions',
        ),
    ]
