# Generated by Django 4.1 on 2022-08-25 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_rename_descriptions_product_discriptions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='discriptions',
            new_name='descriptions',
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
