# Generated by Django 4.1 on 2022-08-25 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_rename_discriptions_product_descriptions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(default=True, max_length=150),
        ),
    ]
